name: Build and Release Tauri App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [AppImage, nsis, dmg]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libsoup2.4-dev libappindicator3-dev librsvg2-dev

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y nsis
          choco install -y wix

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install webkit2gtk

      - name: Build Tauri App
        run: cargo tauri build --target ${{ matrix.target }}

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-tauri-app-${{ matrix.target }}
          path: |
            target/release/bundle/${{ matrix.target }}/*.${{ matrix.target }}
            target/release/bundle/${{ matrix.target }}/*.zip
          retention-days: 5

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/bundle/${{ matrix.target }}/*.${{ matrix.target }}
          asset_name: ${{ matrix.os }}-tauri-app-${{ matrix.target }}.${{ matrix.target }}
          asset_content_type: application/octet-stream
