name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: AppImage
          - os: windows-latest
            target: msi
          - os: macos-latest
            target: dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Install Dependencies (Linux Only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install Dependencies (Windows Only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y wix
          choco install -y visualstudio2019buildtools visualstudio2019-workload-vctools

      - name: Install Dependencies (macOS Only)
        if: matrix.os == 'macos-latest'
        run: brew install --cask xquartz

      - name: Build Tauri app
        run: cargo tauri build --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            src/target/release/bundle/${{ matrix.target }}/*.${{ matrix.target }}
